### ISSUE TITLE
Why this codec isn't installed by default?

### ISSUE THREAD

**Issue by megapro17** [xtknight/vdpau-va-driver-vp9#9]
We are living in stone age, when 8 years old codec isn't accelerated from the box. It is possible to change this situation?

**Comment by Logarithmus** [comment]
@megapro17 I agree with you, it's such a PITA that in pretty much all distros Chromium is built without VAAPI and VP9 support. 99% of users struggle for those few with stone-aged hardware without acceleration support. It should be other way around

**Comment by megapro17** [comment]
Nobody cares because everyone is using Windows where it works flawless. Also Nvidia driver for linux is very laggy shit on kde. Better to stick with wsl that's all
